// <auto-generated />
using BranchTask;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BranchTask.Migrations
{
    [DbContext(typeof(BranchContext))]
    [Migration("20240516050819_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BranchTask.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ArabicDescription")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("ArabicName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("CustomNo")
                        .HasColumnType("int");

                    b.Property<string>("EnglishDescription")
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("EnglishName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(1000)");

                    b.HasKey("BranchId");

                    b.ToTable("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
